name: CI
on:
  push:
    branches: [master]
    paths:
      - 'packages/frontend'
  pull_request:
    branches: [master]
    paths:
      - 'packages/frontend'

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install
      run: yarn install
    - name: "Lint JS/TS"
      run: yarn lint:js
    - name: Lint Templates
      run: yarn lint:hbs
    - name: Lint Styles
      run: yarn lint:sass
    - name: Lint Translations
      run: yarn lint:i18n
    - name: Type Checking
      run: yarn lint:types

  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Test
      run: yarn test



