name: Frontend Deploy Preview
on:
  pull_request:
    branches: [master]
    # paths:
    #   - 'packages/frontend/*'
jobs:
  deploy:
    name: Deploy a preview to Netlify
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs:
    - tests

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install
      run: ./run yarn install
    - name: Install Netlify CLI
      run : npm install -g netlify-cli
    - name: Build
      run: ./run yarn build:production
    - name: Deploy a preview to Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: |
        time netlify deploy

