name: Frontend
on:
  push:
    branches: [master]
    # paths:
    #  - 'packages/frontend'
  pull_request:
    branches: [master]
    paths:
      - 'packages/frontend'

jobs:
  Security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install
      run: npm install -g snyk
    - name: Snyk
      run: cd packages/frontend && snyk test --severity-threshold=high
    
  Quality:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install
      run: ./run yarn install
    - name: "Lint JS/TS"
      run: ./run yarn lint:js
    - name: Lint Templates
      run: ./run yarn lint:hbs
    - name: Lint Styles
      run: ./run yarn lint:sass
    - name: Lint Translations
      run: ./run yarn lint:i18n
    - name: Type Checking
      run: ./run yarn lint:types

  Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Test
      run: time ./run yarn test
      
  Deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Install
      run: ./run yarn install
    - name: Analyze Bundle
      run: time ./run yarn analyze
    - name: Deploy to Netlify
      env: 
        FRONTEND: packages/frontend
      run: |
        mv ${FRONTEND}/coverage public/
        cp ${FRONTEND}/public/bundle.html ${CI_PROJECT_DIR}/packages/frontend/dist/bundle.html
        cp ${FRONTEND}/public/bundle.html public/bundle.html
        time ./scripts/publish

  Deploy_Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: Publish to DockerHub
      env:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
      run: sh ./scripts/dockerhub



